
sever:
  port: 8080
#  servlet:
#    context-path:

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/english_service"
    username: root
    password: 1234

  jackson:
    time-zone: Asia/Ho_Chi_Minh

  jpa:
    hibernate:
      jdbc:
        time_zone: Asia/Ho_Chi_Minh
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "l4xKf4nZKtptcCOz0M/cK8O/2wPc3tSIswIFJguvTOQ+o9clkhqhrqqbCmZNapsG"
  valid-duration: 1 # in hours
  refreshable-duration: 14 # in day